### ISSUE TITLE
How does the extension work?

### ISSUE THREAD

**Issue by orschiro** [theborg3of5/KeepOnePinnedTab#1]
Dear @theborg3of5,

Thanks for this extension! 

I was precisely looking for a way to always keep one pinned tab.

I added your extension, defined a URL in the settings, but then I cannot figure out how the extension works. 

It doesn't produce a pinned tab that is always kept open. 

Could you please give me a hint how to use it?

Thankfully,

Robert

**Comment by theborg3of5** [comment]
The extension should work pretty much out of the box - whenever you open or close a tab, it will check whether there's a pinned tab open with the URL from the settings page (or about:blank if nothing set), and open one if there's not.

What sort of behavior are you seeing?

**Comment by orschiro** [comment]
Dear @theborg3of5,

I installed the extension and expected that it would just work out of the box. 

But after closing the last tab, the browser will still close without keeping a last pinned tab to prevent the browser from forcefully closing.

**Comment by theborg3of5** [comment]
Are installing it from the Chrome Web Store, or are you trying to use the source code here? I'd recommend the Web Store if you're not using it, the extension is here: https://chrome.google.com/webstore/detail/keep-one-pinned-tab/nmcefdbkkkjndgafnlaikloffhdeknod .

If you are using the Web Store version, I have a few clarifying questions:
- Are you seeing any effect from the extension at all?
- If you open a new tab, do you see a pinned tab appear (or is there already one in place)?
- Do you have a custom page set in the extension settings?

**Comment by orschiro** [comment]
Hi @theborg3of5, 

After adding the extension, it adds the following default pinned tab:

![image](https://cloud.githubusercontent.com/assets/170947/12228085/bb7fe720-b836-11e5-90fe-9a00fc71522c.png)

Is that how it's supposed to be? 

I suppose your extension might conflict with [New Tab Page Blank](https://chrome.google.com/webstore/detail/new-tab-page-blank/nenecpikdapoaemacjppaimlcgknbijk) that I've installed, too.

**Comment by theborg3of5** [comment]
That is how the extension works, yes - basically, it's supposed to make sure that tab is always around (which is checked whenever you open a new tab or close one), and whenever that tab is the last one left, it's supposed to open a normal new tab.

I wouldn't expect that extension to affect this behavior, unless the url of the resulting page is something besides chrome://newtab/ (which it appears to be when I just installed it now). That said, could you try temporarily uninstalling that extension and see if that changes anything?

In addition, how are you closing your tabs, and are you also closing the other pinned tabs I see in your screenshot?

**Comment by orschiro** [comment]
@theborg3of5 

Thanks for your elaborated response!

Let's do as follows. I've tested your extension again, set the correct options (my desired URL), kept the other extension enabled, and for now I can say that it is working properly.

I don't know what went wrong initially. 

Having said that, let's close this issue. 

I appreciate your support!

~Robert
