### ISSUE TITLE
Always Use New Tab

### ISSUE THREAD

**Issue by orschiro** [theborg3of5/KeepOnePinnedTab#2]
Dear @theborg3of5,

Might your extension cause the problem described below:

https://github.com/joeyespo/inbox-by-gmail-checker/issues/8

Thankfully,

~Robert

**Comment by theborg3of5** [comment]
Does the issue you reference there happen when you have this extension disabled? It doesn't look like we're opening a new tab when you click the other extension's button, just that it's not recognizing the empty new tab.

**Comment by orschiro** [comment]
@theborg3of5 you are absolutely right. The issue has nothing to do with your extension. I am sorry. Even with the extension being disabled, the other one still does open the website in another new tab. 

~Robert

**Comment by theborg3of5** [comment]
Sounds good, then. I'm going to go ahead and close this issue.

On a side note, I actually have one other extension that I've created (which was originally part of this one, but I split off as I wanted to use one without the other), called [Close Extra New Tabs](https://chrome.google.com/webstore/detail/close-extra-new-tabs/gkaaknlhljkigoogfhaknojpmjnlmcod). It sounds like its behavior may be similar to what you're looking for, so feel free to check it out and see if it helps you out.

**Comment by orschiro** [comment]
@theborg3of5 [Close Extra New Tab](https://chrome.google.com/webstore/detail/close-extra-new-tabs/gkaaknlhljkigoogfhaknojpmjnlmcod/related) is solving my issue. 

Thank you so much!

-Robert
